name: readytotest Smoke (page build + schedule + manual)
on:
 workflow_dispatch:
 page_build:
 schedule:
   - cron: '00 17 * * *' #Daily 17:00 UTC


jobs:
 GitHub-Page-Check:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   steps:
       
        - name: Message
          run: This performs a quick test of my GitHub page and runs after each page build and daily at 17:00 UTC

        - name: Checkout Repo
          uses: actions/checkout@v4.1.1

        - name: Setup Node.js environment
          uses: actions/setup-node@v4.0.1
          with:
            node-version: 20.10.0      
        
        - name: Print system node version and current directory
          run: |
            node -v
            ls

        - name: Test
          uses: cypress-io/github-action@v6
          with:
            command: npm run ready-to-test #readyToTestSmoke.cy

        - name: Upload Report to GitHub
          uses: actions/upload-artifact@v4.0.0
          if: always()
          with:
              name: Test Results + Video
              path: ./cypress/reports/
              if-no-files-found: warn
              retention-days: 60
