name: Playwright GitHub Page (manual)
on: workflow_dispatch

jobs:
 GitHub-Page-Test:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   steps:
       
        - name: Message
          run: echo You have manually initiated the Playwright tests against the production environment

        # Since we are just running this workflow manually against the production URL 
        # I could have put this YAML in the Playwright Repo but I wanted to provide
        # an example of checking out a second repo and showing the syntax for specifying
        # the path and working-directory using the checkout action.

        # Checkout primary repo where this YAML script lives.
        - name: Checkout GitHub Pages Repo
          uses: actions/checkout@v4.1.4
          
        # Check out secondary repo where Playwright scripts live
        - name: Checkout Playwright Repo
          uses: actions/checkout@v4.1.4
          with:
            repository: readytotest/test-playwright
            ref: main
            path: ./playwright-tests #Copy the Playwright repo to this directory within the GitHub page repo
       
        - name: Install dependencies
          working-directory: ./playwright-tests #This is the sub-directory where the Playwright repo was copied to
          run: npm ci

        - name: Print system node version and current directory
          run: |
            node -v
            ls

        - name: Install Playwright Browsers
          working-directory: ./playwright-tests #This is the sub-directory where the Playwright repo was copied to
          run: npx playwright install --with-deps

        - name: Run Playwright tests
          working-directory: ./playwright-tests #This is the sub-directory where the Playwright repo was copied to
          #Tests against https://readytotest.github.io
          run: npx playwright test

        - name: Upload Report to GitHub
          uses: actions/upload-artifact@v4.3.3
          if: always()
          with:
              name: Test Results + Video
              path: ./playwright-tests/playwright-report/
              if-no-files-found: warn
              retention-days: 60