name: Sauce demo Cypress Cloud Parallel (manual only)
on:
 workflow_dispatch:
 
jobs:
 Cypress-Smoke-Test:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   strategy:
    fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    matrix:
      containers: [1, 2] # parallel instances
   steps:
        - name: Checkout Repo
          uses: actions/checkout@v4.1.1

        - name: Test
          uses: cypress-io/github-action@v6
          with:
            command: npm run sauce-demo
            record: true
            parallel: true
          env:
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # overwrite commit message sent to Cypress Cloud
              COMMIT_INFO_MESSAGE: ${{ vars.CYPRESS_CLOUD_RUN_NAME }}