name: Sauce Cypress Cloud Parallel (manual)
on:
 workflow_dispatch:
 
jobs:
 Sauce-Tests-Cypress-Cloud-Parallel:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   strategy:
    fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    matrix:
      containers: [1, 2] # parallel instances
   steps:
        - name: Checkout Repo
          uses: actions/checkout@v4.1.2

        - name: Setup Node.js environment
          uses: actions/setup-node@v4.0.2
          with:
            node-version: 20.10.0      
        
        - name: Print system node version and current directory
          run: |
            node -v
            ls

        - name: Test
          uses: cypress-io/github-action@v6
          with:
            command: npm run sauce-demo
            record: true
            parallel: true
          env:
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # overwrite commit message sent to Cypress Cloud
              COMMIT_INFO_MESSAGE: ${{ vars.CYPRESS_CLOUD_RUN_NAME }}