name: Sauce demo smoke and login tests - Cypress Cloud (manual only)
on:
 workflow_dispatch:
 
jobs:
 Cypress-Smoke-Test:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   strategy:
    fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    matrix:
      containers: [1, 2] # Uses 2 parallel instances
   steps:
        - name: Checkout Repo
          uses: actions/checkout@v4.1.1

        - name: Test
          uses: cypress-io/github-action@v6
          with:
            command: npm run sauce-demo
            record: true
            parallel: true
          env:
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

        - name: Upload Report to GitHub
          uses: actions/upload-artifact@v3.1.3
          if: always()
          with:
              name: Test Results + Video
              path: ./cypress/reports/
              if-no-files-found: warn
              retention-days: 60